version: 1
commandUpdated:
  generators:
    - command: kustomize build .
  updaters:
    # use https://github.com/squaremo/kubeyaml on flux-patch.yaml
    - containerImage:
        command: >-
          cat overlays/$FLUX_WL_NS/flux-patch.yaml |
          kubeyaml image --namespace $FLUX_WL_NS --kind $FLUX_WL_KIND --name $FLUX_WL_NAME --container $FLUX_CONTAINER --image "$FLUX_IMG:$FLUX_TAG"
          > new-flux-patch.yaml &&
          mv new-flux-patch.yaml overlays/$FLUX_WL_NS/flux-patch.yaml
      # policy:
      #   command: >-
      #     cat overlays/$FLUX_WL_NS/flux-patch.yaml |
      #     kubeyaml annotate --namespace $FLUX_WL_NS --kind $FLUX_WL_KIND --name $FLUX_WL_NAME "fluxcd.io/$FLUX_POLICY=$FLUX_POLICY_VALUE"
      #     > new-flux-patch.yaml &&
      #     mv new-flux-patch.yaml overlays/$FLUX_WL_NS/flux-patch.yaml
      policy:
        command: >-
          ls -la overlays/$FLUX_WL_NS > test.txt
          