---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/tag.dt65-events-api: glob:production-*
    fluxcd.io/automated: 'true'
  name: dt65-events-api
  namespace: production
spec:
  template:
    spec:
      containers:
      - image: pehtoorismies/dt65-events-api:production-6c963d1
        name: dt65-events-api
