commonLabels:
  app: prod-dt65

generatorOptions:
  # labels to add to all generated resources
  labels:
    kustomize.generated.resources: prod-dt65
  # annotations to add to all generated resources
  annotations:
    kustomize.generated.resource: prod-dt65

configMapGenerator:
  - name: dt65-config
    literals:
      - authDomain="prod-dt65.eu.auth0.com"
      - jwtAudience="https://api.downtown65.com"

namespace: production

replicas:
- name: dt65-events-api
  count: 2

patches:
  - path: flux-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: dt65-events-api

patchesJson6902:
  - path: ingress-patch.yaml 
    target:
      group: extensions
      version: v1beta1
      kind: Ingress
      name: dt65-events-api

resources:
  - ./../../base
  - namespace.yaml
  - sealed-secrets.yaml
