---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.dt65-events-api: glob:master-*
  name: dt65-events-api
  namespace: development
spec:
  template:
    spec:
      containers:
      - image: pehtoorismies/dt65-events-api:master-9172c01
        name: dt65-events-api
