---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.dt65-events-api: glob:master:*
  name: dt65-events-api
spec:
  template:
    spec:
      containers:
        - image: pehtoorismies/dt65-events-api:master-9956649
          name: dt65-events-api
