---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    fluxcd.io/tag.dt65-events-api: glob:master-*
    fluxcd.io/automated: 'true'
  name: dt65-events-api
  namespace: development
spec:
  template:
    spec:
      containers:
      - image: pehtoorismies/dt65-events-api:master-a8ea0a3
        name: dt65-events-api
