commonLabels:
  env: development

generatorOptions:
  # labels to add to all generated resources
  labels:
    kustomize.generated.resources: dev-dt65
  # annotations to add to all generated resources
  annotations:
    kustomize.generated.resource: dev-dt65

configMapGenerator:
  - name: dt65-config
    literals:
      - authDomain="dev-dt65.eu.auth0.com"
      - jwtAudience="https://graphql-dev.downtown65.com"
      - clientDomain="https://dev.downtown65.events"
      - mailgunDomain="https://api.eu.mailgun.net/v3/mailgun.downtown65.com"
      - mailgunFrom="Kyttäki <hello@downtown65.com>"
namespace: development

patches:
  - path: flux-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: dt65-events-api

patchesJson6902:
  - path: ingress-patch.yaml 
    target:
      group: extensions
      version: v1beta1
      kind: Ingress
      name: dt65-events-api

resources:
  - ./../../base
  - namespace.yaml
  - sealed-secrets.yaml
