commonLabels:
  app: dev-dt65

generatorOptions:
  # labels to add to all generated resources
  labels:
    kustomize.generated.resources: dev-dt65
  # annotations to add to all generated resources
  annotations:
    kustomize.generated.resource: dev-dt65

configMapGenerator:
  - name: dt65-config
    literals:
      - authDomain="dev-dt65.eu.auth0.com"
      - jwtAudience="https://graphql-dev.downtown65.com"

namespace: development

# patchesStrategicMerge:
#   - flux-patch.yaml

resources:
  - ./../../base
  - namespace.yaml
  - sealed-secrets.yaml
# 