apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mongodump
spec:
  schedule: "15 3 * * *"
  jobTemplate:
    metadata:
      name: mongodump
      labels:
        app: cron
    spec:
      template:
        spec: 
          containers:
            - name: mongodump
              image: pehtoorismies/dt65-mongodump:v1.2
              imagePullPolicy: IfNotPresent
              env:
                - name: MONGO_URL
                  valueFrom:
                    secretKeyRef:
                      name: dt65-secret
                      key: mongoUrl
                - name: SERVICE_ACCOUNT_JSON
                  valueFrom:
                    secretKeyRef:
                      name: gce-secret
                      key: service_account_key
                - name: HOST_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: GOOGLE_BUCKET
                  value: "gs://events-downtown65-mongodump"
                - name: GOOGLE_FOLDER
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
          restartPolicy: Never
