apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: weekly-email
spec:
  schedule: "15 7 * * 1"
  jobTemplate:
    metadata:
      name: weekly-email
      labels:
        app: cron
    spec: 
      template:
        spec:
          containers:
          - name: send-weekly
            image: pehtoorismies/dt65-weekly-email:v1.0
            imagePullPolicy: IfNotPresent
            env:
              - name: AUTH0_DOMAIN
                valueFrom:
                  configMapKeyRef:
                    name: dt65-config
                    key: authDomain
              - name: AUTH0_API_IDENTIFIER
                valueFrom:
                  configMapKeyRef:
                    name: dt65-config
                    key: jwtAudience
              - name: SERVER_HOST
                valueFrom:
                  configMapKeyRef:
                    name: dt65-config
                    key: graphqlServer
              - name: AUTH0_CLIENT_ID
                valueFrom:
                  secretKeyRef:
                    name: dt65-secret
                    key: authClientId
              - name: AUTH0_CLIENT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: dt65-secret
                    key: authClientSecret
          restartPolicy: Never
  
