apiVersion: apps/v1
kind: Deployment
metadata:
  name: dt65-events-api
spec:
  replicas: 1
  template:
    metadata:
      name: dt65-events-api
      labels:
        app: dt65-events-api
    spec:
      containers:
        - name: dt65-events-api
          image: pehtoorismies/dt65-events-api:master
          ports:
            - name: graphql
              containerPort: 4000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /graphql?query={liveness}
              port: graphql
          readinessProbe:
            httpGet:
              path: /graphql?query={readiness}
              port: graphql
          env:
            - name: AUTH_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: dt65-config
                  key: authDomain
            - name: JWT_AUDIENCE
              valueFrom:
                configMapKeyRef:
                  name: dt65-config
                  key: jwtAudience
            - name: CLIENT_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: dt65-config
                  key: clientDomain
            - name: MAILGUN_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: dt65-config
                  key: mailgunDomain
            - name: MAILGUN_HOST
              valueFrom:
                configMapKeyRef:
                  name: dt65-config
                  key: mailgunHost
            - name: MAILGUN_FROM
              valueFrom:
                configMapKeyRef:
                  name: dt65-config
                  key: mailgunFrom
            - name: AUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: dt65-secret
                  key: authClientId
            - name: AUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: dt65-secret
                  key: authClientSecret
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: dt65-secret
                  key: mongoUrl
            - name: MAILGUN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: dt65-secret
                  key: mailgunApiKey
            - name: REGISTER_SECRET
              valueFrom:
                secretKeyRef:
                  name: dt65-secret
                  key: registerSecret